// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMdUpj93a7civbvFF-9ana1vHLbD44Da8',
    appId: '1:288605077799:android:f8f765d8edf57a09e3e902',
    messagingSenderId: '288605077799',
    projectId: 'my-cool-chat-app-647e9',
    storageBucket: 'my-cool-chat-app-647e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_I35QHmMAipK36lkHEIb7Z5Bqrdp8w-M',
    appId: '1:288605077799:ios:7eca3ea9d9f3b0f8e3e902',
    messagingSenderId: '288605077799',
    projectId: 'my-cool-chat-app-647e9',
    storageBucket: 'my-cool-chat-app-647e9.firebasestorage.app',
    androidClientId: '288605077799-q5gvmrf58ggcjcr43ebd2n33p71dv0e5.apps.googleusercontent.com',
    iosClientId: '288605077799-9hga5eif7pntlmjcna02mh4iem52cch5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );
}
